### PR TITLE
`class` --> `className` in README

### PR DESCRIPTION
**Pull request by kgoggin**
This confused me for a second when I first saw it, so thought I'd update it to be consistent with the way React wants the attribute named.

Thanks for making this! I'm looking forward to using it!

### CODE REVIEW

**Comment by RobinMalfait** [comment]
Thank you! Could you prefix your commit message with `docs: `?
While this is not 100% correct, since `className` is not an actual `HTML Attribute` it is still better than `class`.

**Comment by RobinMalfait** [comment]
I updated the commit myself and merged it already. You're still marked as a contributor! See: https://github.com/tailwindlabs/tailwindui-react/commit/2727656851d6cc2777062ee39fa2e320d06a000f

**Comment by kgoggin** [comment]
Sorry, missed this! Thanks for the contributor credit 😄. If I do anything else I'll be sure to follow the commit guidelines.

**Comment by RobinMalfait** [comment]
@kgoggin No worries that you missed it, thanks for the contribution! We are actually still experimenting with things regarding commit guidelines. Might change a thing or two. Ideally contributors don't need to worry about it at all.

**Pull request closed without merging**
